In [105]:
import pandas as pd

In [106]:
import os
os.chdir(r"C:\Users\Admin\qa-library-pipeline\data")

In [107]:
Books = pd.read_csv(r"03_Library Systembook.csv")
Customers = pd.read_csv(r"03_Library SystemCustomers.csv")

In [108]:
Customers = Customers[Customers["Customer ID"].notna()]
Customers["Customer ID"] = (
    pd.to_numeric(Customers["Customer ID"], errors="coerce")
    .astype("Int64")
)
Customers["Customer Name"] = Customers["Customer Name"].replace( ["NaN", "nan", ""], pd.NA ) 
Customers["Customer Name"] = Customers["Customer Name"].fillna("NA")
Customers.head()

   Customer ID   Customer Name
0            1        Jane Doe
1            2      John Smith
2            3      Dan Reeves
4            5  William Holden
5            6   Jaztyn Forest

In [109]:
Books[["Customer ID", "Id"]] = Books[["Customer ID", "Id"]].apply(
    lambda col: pd.to_numeric(col, errors="coerce").astype("Int64")
)
Books["Book checkout"] = pd.to_datetime(
    Books["Book checkout"].str.replace('"', '', regex=False),
    dayfirst=True,
    errors="coerce"
)
Books["Book checkout"] = Books["Book checkout"].dt.strftime("%d/%m/%Y")

Books["Days allowed to borrow"] = (
    Books["Days allowed to borrow"]
    .str.extract(r"(\d+)")      
    .astype("Int64")              
    * 7                           
)
Books = Books[Books["Books"].notna()]


Books.head()

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1,Catcher in the Rye,20/02/2023,25/02/2023,14,1
1,2,Lord of the rings the two towers,24/03/2023,21/03/2023,14,2
2,3,Lord of the rings the return of the kind,29/03/2023,25/03/2023,14,3
3,4,The hobbit,02/04/2023,25/03/2023,14,4
4,5,Dune,02/04/2023,25/03/2023,14,5

In [110]:
Customers.head(50)

   Customer ID     Customer Name
0            1          Jane Doe
1            2        John Smith
2            3        Dan Reeves
4            5    William Holden
5            6     Jaztyn Forest
6            7     Jackie Irving
7            8  Matthew Stirling
8            9         Emory Ted

In [111]:
Books.head(50)

,Id,Books,Book checkout,Book Returned,Days allowed to borrow,Customer ID
0,1,Catcher in the Rye,20/02/2023,25/02/2023,14,1
1,2,Lord of the rings the two towers,24/03/2023,21/03/2023,14,2
2,3,Lord of the rings the return of the kind,29/03/2023,25/03/2023,14,3
3,4,The hobbit,02/04/2023,25/03/2023,14,4
4,5,Dune,02/04/2023,25/03/2023,14,5
5,6,Little Women,02/04/2023,01/05/2023,14,1
6,7,IT,10/04/2063,03/04/2023,14,6
7,8,Misery,15/04/2023,03/04/2023,14,7
8,9,Catch 22,15/04/2023,16/04/2023,14,7
9,10,Animal Farm,20/04/2023,24/04/2023,14,2
10,11,1984,23/04/2023,27/04/2023,14,8
11,12,Little Women,02/04/2023,01/05/2023,14,1
12,13,East of Eden,30/04/2023,05/05/2023,14,2
13,14,America Is in the Heart,01/05/2023,07/05/2023,14,3
14,15,Wuthering Heights,01/05/2023,10/05/2023,14,9
15,16,Dark Tales,15/05/2023,01/06/2023,14,2
16,17,The Bloody Chamber,NaN,04/06/2023,14,3
17,18,Les Miserables,03/06/2023,07/06/2023,14,5
18,19,Dracula,10/06/2023,10/07/2023,14,10
19,20,Frankenstein,01/06/2023,20/06/2023,14,2